version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=LOCAL://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=LOCAL://127.0.0.1:9092,DOCKER://kafka:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_INTER_BROKER_LISTENER_NAME=LOCAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LOCAL:PLAINTEXT,DOCKER:PLAINTEXT
    depends_on:
      - zookeeper
  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
  kibana:
    image: kibana:8.6.1
    container_name: kibana
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
  email-messages-consumer:
    build:
      context: /email-messages-consumer-kafka
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: email-messages-consumer
    environment:
      - KAFKA_ADDRESS=kafka:9093
      - ELASTIC_ADDRESS=elasticsearch:9200
    depends_on:
      - kafka
      - elasticsearch
